### ISSUE TITLE
req for release v1.0

### ISSUE THREAD

**Issue by regisrex** [regisrex/string-hunt#14]
The algos and everything required for v1.0 are ready,
Can we release? @pacifiquem

**Comment by pacifiquem** [comment]
Sure @regisrex everything looks good to me. :+1:

**Comment by pacifiquem** [comment]
Complex data must be added for users to test it.

**Comment by regisrex** [comment]
Okay

**Comment by pacifiquem** [comment]
We're ready to go, requested changes appeared in #16
