### ISSUE TITLE
expect the query to be sthi like `name:johndoe` or `johndoe` and also keys must be optional

### ISSUE THREAD

**Issue by regisrex** [regisrex/string-hunt#24]
![image](https://github.com/regisrex/string-hunt/assets/94565752/630c5cf7-25fc-4d0f-9987-3636e9bf271f)
Keys can be added or not, to mean we should maintain how the module was working in past versions

**Comment by regisrex** [comment]
After this is fixed, issue #23  can be fixed too

**Comment by pacifiquem** [comment]
Sure @regisrex I'm on it.
